require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.harpoon")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.comments")
require("core.plugin_config.null-ls")
require("core.plugin_config.vim-fugitive")
-- require("core.plugin_config.nvim-dap")
require("core.plugin_config.gitsigns")
require("core.plugin_config.diffview")
require("core.plugin_config.barbar")
